### PR TITLE
Closes #8 | Refactor Auth Structure

### LINKED ISSUE #8: Chore: Refactor Auth Component

### PR DESCRIPTION
**Pull request by arinze19**

### CODE REVIEW

**Review by heisdeku — CHANGES_REQUESTED** [review]
Hey @arinze19 I think there's an issue that makes netlify build fails but apart from that nice work done by following BEM standards and the file structure.

Also, noticed the LogIn component and route in the App.js file, which has a path of "/auth/login", thought it was meant to be a modal.

Could it be in a modal and still be a route, kindly explain?

Apart from the build which fails it and the lack of proper context on the mentioned above stuff , I'm good to go with this.

So that I could do the auth logic completely

**Comment by arinze19** [comment]
yeah it could be just a component. going to create another issue to fix that.

**Review by heisdeku — APPROVED** [review]

**Comment by heisdeku** [comment]
@arinze19 looks good to me, well done, now time for me for connect the api with it, cos it works now

**Comment by arinze19** [comment]
Yeah open an issue in that so we know what you're working on

**Comment by heisdeku** [comment]
could this be merged right now, so that i will pull

**Review by heisdeku — APPROVED** [review]

**Pull request merged**
