### PR TITLE
Create Auth Component

### LINKED ISSUE #2: Create Auth Component
- Create basic auth component with `email`, `name`, `password` fields. 
- Up to you to decide if this should route to a `/auth` page or be a modal
- Ref: [selfish-twentys](https://selfish-twentys.netlify.app/auth)

### PR DESCRIPTION
**Pull request by heisdeku**
Created both Authentication (Login & Signup) components. Created an API object wrapper which contains all user & authentication methods.

Modified the code for the Modal Component to be reusable and free to use.  NB: there is a bug with the modal component for the background picker, even though it accomplishes my task. I will get back to fixing the bug

Also some few cleanups 

@arinze19  also deploy the backend to HEROKU for me to change the BASE_URL has I had issues running the server on a new system btw.

### CODE REVIEW

**Comment by arinze19** [comment]
1. few issues on desktop. The Auth modal isn't centered and at this moment I can't seem to focus on the input fields of the auth component - this is likely caused by setting the `pointer-events: true` or the `z-index` issues. 
2. I was hoping we could do this without having to bring in react router. maybe have a state that depending on which button [background / auth] would insert the respective component into the modal.
3. will set up the backend on heroku by tomorrow. Take your time with the issue, no pressure. you've done well so far

**Comment by TildaDares** [comment]
@arinze19 @heisdeku I think each PR should contain just one change or related changes. It's hard to review a PR that's fixing more than one thing. What do you think?

@heisdeku Amazing work.

**Comment by arinze19** [comment]
Yeah that’s a good idea. Will incorporate that into subsequent issues going forward

**Comment by heisdeku** [comment]
@arinze19 I have fixed the issue of the modal display on desktop and mobile

Also, for  the modal, I refactored the currently existing flow and  did it the way you recommended in your earlier comment above by checking the type of modal state being called for

Lastly, when are you dropping heroku link for boys

**Comment by heisdeku** [comment]
@TildaDares i like the suggestion that a PR should only contain a feature, had to include the modal feature in this because it's related to the authentication component as the Authentication Component were rendered in a modal

Also, thanks

**Comment by arinze19** [comment]
@heisdeku okay here's a link to the heroku app [https://bookmark-er.herokuapp.com/api/v1](https://bookmark-er.herokuapp.com/api/v1).

**Review by arinze19 — APPROVED** [review]
LGTM.  although you still have to take out the react router component as we wont be using routes in this project
@TildaDares what do you think

**Review by TildaDares — APPROVED** [review]
LGTM!

**Pull request merged**
